### ISSUE TITLE
VS2012 SAFESEH:NO  error on building project

### ISSUE THREAD

**Issue by Razultull** [danoli3/Multithreaded-Ray-Tracer#3]
Project was imported and updated to "2012" and the following errors were encountered in the output window. 

http://pastie.org/private/dxosj3bptwgt0npdwnmsya

After following these instructions:

"Add the following:
SAFESEH:NO

To set this linker option in the Visual Studio development environment
Open the project's Property Pages dialog box. For details, see Setting Visual C++ Project Properties.

Click the Linker folder.

Click the Command Line property page.

Type the option into the Additional Options box.
"

the following errors were encountered:

http://pastie.org/private/d55wmly0eldfmiz4m9qa

**Comment by danoli3** [comment]
1>LINK : fatal error LNK1104: cannot open file 'SAFESEH:NO.obj
Seems to indicate that somehow this has become a class to build.

Hmm well try and remove the SAFESEH:NO and try the following:

"Option does not need to be enterred in Command Line/Additional Options
Go to "Linker/Advanced/Image Has Save Exception handlers" "
http://msdn.microsoft.com/en-us/library/9a89h429(v=vs.80).aspx

**Comment by Razultull** [comment]
Hi due to the urgency of me having to access and build the ray tracer I installed 2010 and got it to build. If you would like me to pursue the matter I can reinstall 2012 and try and solve it, but if it’s not really required I am quite comfortable with leaving it unsolved hehe.  I am VERY grateful for the time you have taken to help me and I’m sorry if you feel I wasted your time. Please do tell me if you want me to try and solve it.

Best, 
Rahul Chatterjee

**Comment by danoli3** [comment]
Assigned and should get 2012 working by tomorrow

**Comment by danoli3** [comment]
46f5cc3f8e6dacdec463bd1e9b4d9e0559f8eff8 fixed
